#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tiki"
name = "Tiki"
description.en = "Wiki-based, content management system"
description.fr = "Système de gestion de contenu basé sur Wiki"

version = "28.4~ynh1"

maintainers = []

[upstream]
license = "LGPL-2.1-only"
website = "https://tiki.org/"
demo = "https://tiki.org/Try-Tiki"
admindoc = "https://doc.tiki.org"
code = "https://gitlab.com/tikiwiki/tiki/"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/tiki"

    [install.release_cycle]
    ask.en = "Upgrade cycle"
    ask.fr = "Cycle de mises à jours"
    help.en = "Every 3 version is an LTS. LTS versions are supported for 5 years"
    help.fr = "Toutes les 3 versions sont des LTS qui sont maintenues pendant 5 ans"
    type = "select"
    choices.longterm = "Install latest Long Term Support version (recommended)"
    choices.regular = "Install latest version"
    default = "longterm"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://sourceforge.net/projects/tikiwiki/files/Tiki_28.x_Castor/28.4/tiki-28.4.tar.gz/download"
    sha256 = "0078f06445e02be7f16d7c2d0b6d2117ae1d5029daded4f8141a96e59d8a4ae0"
    format = "tar.gz"
    prefetch = false

    [resources.sources.lts]
    url = "https://sourceforge.net/projects/tikiwiki/files/Tiki_27.x_Miaplacidus/27.3/tiki-27.3.tar.gz/download"
    sha256 = "4c9dcd58e9df68a4c0c02cedea71975dd311aa8f87583f32809b7bb859788b69"
    format = "tar.gz"
    prefetch = false

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "tesseract-ocr, imagemagick, mariadb-server, php8.3-bz2, php8.3-curl, php8.3-gd, php8.3-zip, php8.3-mysql, php8.3-xml, php8.3-mbstring, php8.3-intl, php8.3-tidy"

    [resources.database]
    type = "mysql"
