#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tiki"
name = "Tiki"
description.en = "Wiki-based, content management system"
description.fr = "Système de gestion de contenu basé sur Wiki"

version = "28.3~ynh1"

maintainers = []

[upstream]
license = "LGPL-2.1-only"
website = "https://tiki.org/"
demo = "https://tiki.org/Try-Tiki"
admindoc = "https://doc.tiki.org"
code = "https://gitlab.com/tikiwiki/tiki/"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/tiki"

    [install.release_cycle]
    ask.en = "Upgrade cycle"
    ask.fr = "Cycle de mises à jours"
    help.en = "Every 3 version is an LTS. LTS versions are supported for 5 years"
    help.fr = "Toutes les 3 versions sont des LTS qui sont maintenues pendant 5 ans"
    type = "select"
    choices.longterm = "Install latest Long Term Support version (recommended)"
    choices.regular = "Install latest version"
    default = "longterm"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://sourceforge.net/projects/tikiwiki/files/Tiki_28.x_Castor/28.3/tiki-28.3.tar.gz/download"
    sha256 = "ee54bfe8514c7643713cc8687b31c686b6c2c6679a31f7487c86d4c91ef77b8c"
    format = "tar.gz"
    prefetch = false

    [resources.sources.lts]
    url = "https://sourceforge.net/projects/tikiwiki/files/Tiki_27.x_Miaplacidus/27.2/tiki-27.2.tar.gz/download"
    sha256 = "4c242f39cfe4e8e1eb8c6509b4adf2ab15106904b17067dbfb875a85424bbb0e"
    format = "tar.gz"
    prefetch = false

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "tesseract-ocr, imagemagick, mariadb-server, php8.1-bz2, php8.1-curl, php8.1-gd, php8.1-zip, php8.1-mysql, php8.1-xml, php8.1-mbstring, php8.1-intl, php8.1-tidy"

    [resources.database]
    type = "mysql"
