#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=256M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
source_id_to_use="main"
if [[ "$release_cycle" == "longterm" ]]
then
	source_id_to_use="lts"
fi

ynh_setup_source --dest_dir="$install_dir" --source_id="$source_id_to_use"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
	# Create database configuration file
	php_exec_as_app console.php database:configure "$app" "$db_pwd" "$app"

	# Create database contents
	php_exec_as_app console.php database:install

	# Set default database directory
	sed -i -e "s#storage/fgal#$data_dir#" lib/prefs/fgal.php

	# Lock installer
	php_exec_as_app console.php installer:lock

	# Create data index
	php_exec_as_app console.php index:rebuild

	# Set on Long Term Support versions
	if [[ "$release_cycle" == "longterm" ]]
	then
		php_exec_as_app console.php preferences:set tiki_release_cycle longterm
	fi

	# Create user
	php_exec_as_app console.php users:password --no-interaction admin "$password"
popd

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
