#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=php_upload_max_filesize --value=256M

ynh_app_setting_set_default --key=release_cycle --value=longterm

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
source_id_to_use="main"
if [[ "$release_cycle" == "longterm" ]]
then
	source_id_to_use="lts"
fi

ynh_setup_source --dest_dir="$install_dir" --source_id="$source_id_to_use"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# UPGRADE APP
#=================================================
ynh_script_progression "Upgrading $app..."

pushd "$install_dir"
	# Update database
	php_exec_as_app console.php database:update
popd

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
